/**
 * Complete Balatro 1.0.1o Jokers Knowledge Base (All 150 Jokers)
 * 完整《小丑牌》150张小丑牌全量数据库与特性定义
 */

export type JokerCategory =
  | 'CHIPS'
  | 'FLAT_MULT'
  | 'XMULT'
  | 'RETRIGGER'
  | 'HAND_MODIFIER'
  | 'ECONOMY'
  | 'UTILITY'
  | 'BLUEPRINT'
  | 'BRAINSTORM';

export type JokerTriggerPhase =
  | 'played_card'   // Triggers during Played Cards phase for each scoring card
  | 'held_card'     // Triggers during Held Cards phase for each held card
  | 'joker_main'    // Triggers during Jokers phase from left to right
  | 'retrigger'     // Retriggers played or held cards
  | 'hand_modifier' // Modifies poker hand detection rules (Four Fingers, Shortcut, etc.)
  | 'passive';      // Economy or game rules (Chicot, Golden Joker, etc.)

export interface JokerDefinition {
  key: string;
  name: string;
  nameZh: string;
  rarity: 1 | 2 | 3 | 4; // 1: Common, 2: Uncommon, 3: Rare, 4: Legendary
  cost: number;
  category: JokerCategory;
  triggerPhase: JokerTriggerPhase;
  blueprintCompat: boolean;
  description: string;
  descriptionZh: string;
  baseChips?: number;
  baseMult?: number;
  baseXMult?: number;
  handType?: string;
  suit?: 'Spades' | 'Hearts' | 'Clubs' | 'Diamonds';
  faceOnly?: boolean;
  ranks?: string[];
}

export const BALATRO_JOKERS: Record<string, JokerDefinition> = {
  "j_joker": {
    "key": "j_joker",
    "name": "Joker",
    "nameZh": "小丑",
    "rarity": 1,
    "cost": 2,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 4
  },
  "j_greedy_joker": {
    "key": "j_greedy_joker",
    "name": "Greedy Joker",
    "nameZh": "贪婪小丑",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的",
    "baseMult": 3,
    "suit": "Diamonds"
  },
  "j_lusty_joker": {
    "key": "j_lusty_joker",
    "name": "Lusty Joker",
    "nameZh": "色欲小丑",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的",
    "baseMult": 3,
    "suit": "Hearts"
  },
  "j_wrathful_joker": {
    "key": "j_wrathful_joker",
    "name": "Wrathful Joker",
    "nameZh": "愤怒小丑",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的",
    "baseMult": 3,
    "suit": "Spades"
  },
  "j_gluttenous_joker": {
    "key": "j_gluttenous_joker",
    "name": "Gluttonous Joker",
    "nameZh": "暴食小丑",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的",
    "baseMult": 3,
    "suit": "Clubs"
  },
  "j_jolly": {
    "key": "j_jolly",
    "name": "Jolly Joker",
    "nameZh": "开心小丑",
    "rarity": 1,
    "cost": 3,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseMult": 8,
    "handType": "Pair"
  },
  "j_zany": {
    "key": "j_zany",
    "name": "Zany Joker",
    "nameZh": "古怪小丑",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseMult": 12,
    "handType": "Three of a Kind"
  },
  "j_mad": {
    "key": "j_mad",
    "name": "Mad Joker",
    "nameZh": "疯狂小丑",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseMult": 10,
    "handType": "Two Pair"
  },
  "j_crazy": {
    "key": "j_crazy",
    "name": "Crazy Joker",
    "nameZh": "狂野小丑",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseMult": 12,
    "handType": "Straight"
  },
  "j_droll": {
    "key": "j_droll",
    "name": "Droll Joker",
    "nameZh": "滑稽小丑",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseMult": 10,
    "handType": "Flush"
  },
  "j_sly": {
    "key": "j_sly",
    "name": "Sly Joker",
    "nameZh": "奸诈小丑",
    "rarity": 1,
    "cost": 3,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseChips": 50,
    "handType": "Pair"
  },
  "j_wily": {
    "key": "j_wily",
    "name": "Wily Joker",
    "nameZh": "狡猾小丑",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseChips": 100,
    "handType": "Three of a Kind"
  },
  "j_clever": {
    "key": "j_clever",
    "name": "Clever Joker",
    "nameZh": "聪敏小丑",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseChips": 80,
    "handType": "Two Pair"
  },
  "j_devious": {
    "key": "j_devious",
    "name": "Devious Joker",
    "nameZh": "阴险小丑",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseChips": 100,
    "handType": "Straight"
  },
  "j_crafty": {
    "key": "j_crafty",
    "name": "Crafty Joker",
    "nameZh": "精明小丑",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseChips": 80,
    "handType": "Flush"
  },
  "j_half": {
    "key": "j_half",
    "name": "Half Joker",
    "nameZh": "半张小丑",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌",
    "baseMult": 20
  },
  "j_stencil": {
    "key": "j_stencil",
    "name": "Joker Stencil",
    "nameZh": "模具小丑",
    "rarity": 2,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_four_fingers": {
    "key": "j_four_fingers",
    "name": "Four Fingers",
    "nameZh": "四指",
    "rarity": 2,
    "cost": 7,
    "category": "HAND_MODIFIER",
    "triggerPhase": "hand_modifier",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_mime": {
    "key": "j_mime",
    "name": "Mime",
    "nameZh": "哑剧演员",
    "rarity": 2,
    "cost": 5,
    "category": "RETRIGGER",
    "triggerPhase": "retrigger",
    "blueprintCompat": true,
    "description": "Retrigger all",
    "descriptionZh": "重新触发所有"
  },
  "j_credit_card": {
    "key": "j_credit_card",
    "name": "Credit Card",
    "nameZh": "信用卡",
    "rarity": 1,
    "cost": 1,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "Go up to",
    "descriptionZh": "可以负债"
  },
  "j_ceremonial": {
    "key": "j_ceremonial",
    "name": "Ceremonial Dagger",
    "nameZh": "仪式匕首",
    "rarity": 2,
    "cost": 6,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 0
  },
  "j_banner": {
    "key": "j_banner",
    "name": "Banner",
    "nameZh": "旗帜",
    "rarity": 1,
    "cost": 5,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "每一个剩余的",
    "baseChips": 30
  },
  "j_mystic_summit": {
    "key": "j_mystic_summit",
    "name": "Mystic Summit",
    "nameZh": "神秘之峰",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 15
  },
  "j_marble": {
    "key": "j_marble",
    "name": "Marble Joker",
    "nameZh": "大理石小丑",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_loyalty_card": {
    "key": "j_loyalty_card",
    "name": "Loyalty Card",
    "nameZh": "积分卡",
    "rarity": 2,
    "cost": 5,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 4.0
  },
  "j_8_ball": {
    "key": "j_8_ball",
    "name": "8 Ball",
    "nameZh": "八号球",
    "rarity": 1,
    "cost": 5,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_misprint": {
    "key": "j_misprint",
    "name": "Misprint",
    "nameZh": "印错小丑",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 11
  },
  "j_dusk": {
    "key": "j_dusk",
    "name": "Dusk",
    "nameZh": "黄昏",
    "rarity": 2,
    "cost": 5,
    "category": "RETRIGGER",
    "triggerPhase": "retrigger",
    "blueprintCompat": true,
    "description": "Retrigger all played",
    "descriptionZh": "每回合的"
  },
  "j_raised_fist": {
    "key": "j_raised_fist",
    "name": "Raised Fist",
    "nameZh": "致胜之拳",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "held_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_chaos": {
    "key": "j_chaos",
    "name": "Chaos the Clown",
    "nameZh": "Клоун Хаос",
    "rarity": 1,
    "cost": 4,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "每次商店"
  },
  "j_fibonacci": {
    "key": "j_fibonacci",
    "name": "Fibonacci",
    "nameZh": "斐波那契",
    "rarity": 2,
    "cost": 8,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "打出的每一张",
    "baseMult": 8,
    "ranks": [
      "A",
      "2",
      "3",
      "5",
      "8"
    ]
  },
  "j_steel_joker": {
    "key": "j_steel_joker",
    "name": "Steel Joker",
    "nameZh": "钢铁小丑",
    "rarity": 2,
    "cost": 7,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 0.2
  },
  "j_scary_face": {
    "key": "j_scary_face",
    "name": "Scary Face",
    "nameZh": "恐怖面孔",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 30,
    "faceOnly": true
  },
  "j_abstract": {
    "key": "j_abstract",
    "name": "Abstract Joker",
    "nameZh": "抽象小丑",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 3
  },
  "j_delayed_grat": {
    "key": "j_delayed_grat",
    "name": "Delayed Gratification",
    "nameZh": "延迟满足",
    "rarity": 1,
    "cost": 4,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "如果在回合结束时"
  },
  "j_hack": {
    "key": "j_hack",
    "name": "Hack",
    "nameZh": "烂脱口秀演员",
    "rarity": 2,
    "cost": 6,
    "category": "RETRIGGER",
    "triggerPhase": "retrigger",
    "blueprintCompat": true,
    "description": "Retrigger each played",
    "descriptionZh": "重新触发 所有打出的",
    "ranks": [
      "2",
      "3",
      "4",
      "5"
    ]
  },
  "j_pareidolia": {
    "key": "j_pareidolia",
    "name": "Pareidolia",
    "nameZh": "幻视",
    "rarity": 2,
    "cost": 5,
    "category": "HAND_MODIFIER",
    "triggerPhase": "hand_modifier",
    "blueprintCompat": false,
    "description": "All cards are considered",
    "descriptionZh": "所有卡牌 均视为"
  },
  "j_gros_michel": {
    "key": "j_gros_michel",
    "name": "Gros Michel",
    "nameZh": "大麦克香蕉",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 15
  },
  "j_even_steven": {
    "key": "j_even_steven",
    "name": "Even Steven",
    "nameZh": "偶数史蒂文",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的点数为",
    "baseMult": 4,
    "ranks": [
      "2",
      "4",
      "6",
      "8",
      "10"
    ]
  },
  "j_odd_todd": {
    "key": "j_odd_todd",
    "name": "Odd Todd",
    "nameZh": "奇数托德",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的点数为",
    "baseChips": 31,
    "ranks": [
      "A",
      "3",
      "5",
      "7",
      "9"
    ]
  },
  "j_scholar": {
    "key": "j_scholar",
    "name": "Scholar",
    "nameZh": "学者",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 20,
    "baseMult": 4,
    "ranks": [
      "A"
    ]
  },
  "j_business": {
    "key": "j_business",
    "name": "Business Card",
    "nameZh": "名片",
    "rarity": 1,
    "cost": 4,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_supernova": {
    "key": "j_supernova",
    "name": "Supernova",
    "nameZh": "超新星",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "Adds the number of times",
    "descriptionZh": "",
    "baseMult": 1
  },
  "j_ride_the_bus": {
    "key": "j_ride_the_bus",
    "name": "Ride the Bus",
    "nameZh": "搭乘巴士",
    "rarity": 1,
    "cost": 6,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "连续打出没有",
    "baseMult": 1
  },
  "j_space": {
    "key": "j_space",
    "name": "Space Joker",
    "nameZh": "太空小丑",
    "rarity": 2,
    "cost": 5,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_egg": {
    "key": "j_egg",
    "name": "Egg",
    "nameZh": "鸡蛋",
    "rarity": 1,
    "cost": 4,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "在回合结束时"
  },
  "j_burglar": {
    "key": "j_burglar",
    "name": "Burglar",
    "nameZh": "窃贼",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_blackboard": {
    "key": "j_blackboard",
    "name": "Blackboard",
    "nameZh": "黑板",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果留在手牌中的",
    "baseXMult": 3.0
  },
  "j_runner": {
    "key": "j_runner",
    "name": "Runner",
    "nameZh": "跑步选手",
    "rarity": 1,
    "cost": 5,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中包含",
    "baseChips": 15
  },
  "j_ice_cream": {
    "key": "j_ice_cream",
    "name": "Ice Cream",
    "nameZh": "冰淇淋",
    "rarity": 1,
    "cost": 5,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 100
  },
  "j_dna": {
    "key": "j_dna",
    "name": "DNA",
    "nameZh": "DNA",
    "rarity": 3,
    "cost": 8,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_splash": {
    "key": "j_splash",
    "name": "Splash",
    "nameZh": "飞溅",
    "rarity": 1,
    "cost": 3,
    "category": "HAND_MODIFIER",
    "triggerPhase": "hand_modifier",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_blue_joker": {
    "key": "j_blue_joker",
    "name": "Blue Joker",
    "nameZh": "蓝色小丑",
    "rarity": 1,
    "cost": 5,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 2
  },
  "j_sixth_sense": {
    "key": "j_sixth_sense",
    "name": "Sixth Sense",
    "nameZh": "第六感",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_constellation": {
    "key": "j_constellation",
    "name": "Constellation",
    "nameZh": "星座",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "This Joker gains",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_hiker": {
    "key": "j_hiker",
    "name": "Hiker",
    "nameZh": "徒步者",
    "rarity": 2,
    "cost": 5,
    "category": "CHIPS",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "打出的每一张牌",
    "baseChips": 5
  },
  "j_faceless": {
    "key": "j_faceless",
    "name": "Faceless Joker",
    "nameZh": "无面小丑",
    "rarity": 1,
    "cost": 4,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果同时弃掉"
  },
  "j_green_joker": {
    "key": "j_green_joker",
    "name": "Green Joker",
    "nameZh": "绿色小丑",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 1
  },
  "j_superposition": {
    "key": "j_superposition",
    "name": "Superposition",
    "nameZh": "叠加态",
    "rarity": 1,
    "cost": 4,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中包含"
  },
  "j_todo_list": {
    "key": "j_todo_list",
    "name": "To Do List",
    "nameZh": "待办清单",
    "rarity": 1,
    "cost": 4,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_cavendish": {
    "key": "j_cavendish",
    "name": "Cavendish",
    "nameZh": "卡文迪什",
    "rarity": 1,
    "cost": 4,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 3.0
  },
  "j_card_sharp": {
    "key": "j_card_sharp",
    "name": "Card Sharp",
    "nameZh": "老千小丑",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 3.0
  },
  "j_red_card": {
    "key": "j_red_card",
    "name": "Red Card",
    "nameZh": "红牌",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "This Joker gains",
    "descriptionZh": "",
    "baseMult": 3
  },
  "j_madness": {
    "key": "j_madness",
    "name": "Madness",
    "nameZh": "疯狂",
    "rarity": 2,
    "cost": 7,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_square": {
    "key": "j_square",
    "name": "Square Joker",
    "nameZh": "方形小丑",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌",
    "baseChips": 4
  },
  "j_seance": {
    "key": "j_seance",
    "name": "Séance",
    "nameZh": "通灵",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_riff_raff": {
    "key": "j_riff_raff",
    "name": "Riff-Raff",
    "nameZh": "乌合之众",
    "rarity": 1,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_vampire": {
    "key": "j_vampire",
    "name": "Vampire",
    "nameZh": "吸血鬼",
    "rarity": 2,
    "cost": 7,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_shortcut": {
    "key": "j_shortcut",
    "name": "Shortcut",
    "nameZh": "捷径",
    "rarity": 2,
    "cost": 7,
    "category": "HAND_MODIFIER",
    "triggerPhase": "hand_modifier",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_hologram": {
    "key": "j_hologram",
    "name": "Hologram",
    "nameZh": "全息影像",
    "rarity": 2,
    "cost": 7,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_vagabond": {
    "key": "j_vagabond",
    "name": "Vagabond",
    "nameZh": "流浪者",
    "rarity": 3,
    "cost": 8,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果在出牌时"
  },
  "j_baron": {
    "key": "j_baron",
    "name": "Baron",
    "nameZh": "男爵",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "held_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "留在手牌中的",
    "baseXMult": 1.5,
    "ranks": [
      "K"
    ]
  },
  "j_cloud_9": {
    "key": "j_cloud_9",
    "name": "Cloud 9",
    "nameZh": "9霄云外",
    "rarity": 2,
    "cost": 7,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "每个回合结束时"
  },
  "j_rocket": {
    "key": "j_rocket",
    "name": "Rocket",
    "nameZh": "火箭",
    "rarity": 2,
    "cost": 6,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_obelisk": {
    "key": "j_obelisk",
    "name": "Obelisk",
    "nameZh": "方尖石塔",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "连续打出不是你",
    "baseXMult": 1.0
  },
  "j_midas_mask": {
    "key": "j_midas_mask",
    "name": "Midas Mask",
    "nameZh": "迈达斯面具",
    "rarity": 2,
    "cost": 7,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_luchador": {
    "key": "j_luchador",
    "name": "Luchador",
    "nameZh": "摔跤手",
    "rarity": 2,
    "cost": 5,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "Sell this card to disable the current",
    "descriptionZh": "售出这张小丑牌 会消除当前回合中"
  },
  "j_photograph": {
    "key": "j_photograph",
    "name": "Photograph",
    "nameZh": "照片",
    "rarity": 1,
    "cost": 5,
    "category": "XMULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 2.0,
    "faceOnly": true
  },
  "j_gift": {
    "key": "j_gift",
    "name": "Gift Card",
    "nameZh": "礼品卡",
    "rarity": 2,
    "cost": 6,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "在每回合结束时"
  },
  "j_turtle_bean": {
    "key": "j_turtle_bean",
    "name": "Turtle Bean",
    "nameZh": "黑龟豆",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_erosion": {
    "key": "j_erosion",
    "name": "Erosion",
    "nameZh": "侵蚀",
    "rarity": 2,
    "cost": 6,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "在你的牌组中",
    "baseMult": 4
  },
  "j_reserved_parking": {
    "key": "j_reserved_parking",
    "name": "Reserved Parking",
    "nameZh": "私人车位",
    "rarity": 1,
    "cost": 6,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "留在手牌中的"
  },
  "j_mail": {
    "key": "j_mail",
    "name": "Mail-In Rebate",
    "nameZh": "邮件回扣",
    "rarity": 1,
    "cost": 4,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_to_the_moon": {
    "key": "j_to_the_moon",
    "name": "To the Moon",
    "nameZh": "冲向月球",
    "rarity": 2,
    "cost": 5,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "回合结束时"
  },
  "j_hallucination": {
    "key": "j_hallucination",
    "name": "Hallucination",
    "nameZh": "幻觉",
    "rarity": 1,
    "cost": 4,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_fortune_teller": {
    "key": "j_fortune_teller",
    "name": "Fortune Teller",
    "nameZh": "占卜师",
    "rarity": 1,
    "cost": 6,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 1
  },
  "j_juggler": {
    "key": "j_juggler",
    "name": "Juggler",
    "nameZh": "杂耍师",
    "rarity": 1,
    "cost": 4,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_drunkard": {
    "key": "j_drunkard",
    "name": "Drunkard",
    "nameZh": "醉汉",
    "rarity": 1,
    "cost": 4,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "每回合"
  },
  "j_stone": {
    "key": "j_stone",
    "name": "Stone Joker",
    "nameZh": "石头小丑",
    "rarity": 2,
    "cost": 6,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 25
  },
  "j_golden": {
    "key": "j_golden",
    "name": "Golden Joker",
    "nameZh": "黄金小丑",
    "rarity": 1,
    "cost": 6,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "在回合结束时"
  },
  "j_lucky_cat": {
    "key": "j_lucky_cat",
    "name": "Lucky Cat",
    "nameZh": "招财猫",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_baseball": {
    "key": "j_baseball",
    "name": "Baseball Card",
    "nameZh": "棒球卡",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.5
  },
  "j_bull": {
    "key": "j_bull",
    "name": "Bull",
    "nameZh": "斗牛",
    "rarity": 2,
    "cost": 6,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 2
  },
  "j_diet_cola": {
    "key": "j_diet_cola",
    "name": "Diet Cola",
    "nameZh": "零糖可乐",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "Sell this card to create a free",
    "descriptionZh": "售出这牌就可以 创建一个免费的"
  },
  "j_trading": {
    "key": "j_trading",
    "name": "Trading Card",
    "nameZh": "交易卡",
    "rarity": 2,
    "cost": 6,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_flash": {
    "key": "j_flash",
    "name": "Flash Card",
    "nameZh": "闪示卡",
    "rarity": 2,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 2
  },
  "j_popcorn": {
    "key": "j_popcorn",
    "name": "Popcorn",
    "nameZh": "爆米花",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 20
  },
  "j_trousers": {
    "key": "j_trousers",
    "name": "Spare Trousers",
    "nameZh": "备用裤子",
    "rarity": 2,
    "cost": 6,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中包含",
    "baseMult": 2
  },
  "j_ancient": {
    "key": "j_ancient",
    "name": "Ancient Joker",
    "nameZh": "古老小丑",
    "rarity": 3,
    "cost": 8,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Each played card with",
    "descriptionZh": "",
    "baseXMult": 1.5
  },
  "j_ramen": {
    "key": "j_ramen",
    "name": "Ramen",
    "nameZh": "拉面",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 2.0
  },
  "j_walkie_talkie": {
    "key": "j_walkie_talkie",
    "name": "Walkie Talkie",
    "nameZh": "对讲机",
    "rarity": 1,
    "cost": 4,
    "category": "CHIPS",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 10,
    "baseMult": 4,
    "ranks": [
      "10",
      "4"
    ]
  },
  "j_selzer": {
    "key": "j_selzer",
    "name": "Seltzer",
    "nameZh": "苏打水",
    "rarity": 2,
    "cost": 6,
    "category": "RETRIGGER",
    "triggerPhase": "retrigger",
    "blueprintCompat": true,
    "description": "Retrigger all cards played for",
    "descriptionZh": ""
  },
  "j_castle": {
    "key": "j_castle",
    "name": "Castle",
    "nameZh": "城堡",
    "rarity": 2,
    "cost": 6,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 3
  },
  "j_smiley": {
    "key": "j_smiley",
    "name": "Smiley Face",
    "nameZh": "微笑表情",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 5,
    "faceOnly": true
  },
  "j_campfire": {
    "key": "j_campfire",
    "name": "Campfire",
    "nameZh": "篝火",
    "rarity": 3,
    "cost": 9,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_ticket": {
    "key": "j_ticket",
    "name": "Golden Ticket",
    "nameZh": "黄金门票",
    "rarity": 1,
    "cost": 5,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_mr_bones": {
    "key": "j_mr_bones",
    "name": "Mr. Bones",
    "nameZh": "骷髅先生",
    "rarity": 2,
    "cost": 5,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "Prevents Death if chips scored",
    "descriptionZh": "如果最终得到的 筹码至少是"
  },
  "j_acrobat": {
    "key": "j_acrobat",
    "name": "Acrobat",
    "nameZh": "杂技演员",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "每回合的最后一次",
    "baseXMult": 3.0
  },
  "j_sock_and_buskin": {
    "key": "j_sock_and_buskin",
    "name": "Sock and Buskin",
    "nameZh": "喜与悲",
    "rarity": 2,
    "cost": 6,
    "category": "RETRIGGER",
    "triggerPhase": "retrigger",
    "blueprintCompat": true,
    "description": "Retrigger all",
    "descriptionZh": "重新触发所有",
    "faceOnly": true
  },
  "j_swashbuckler": {
    "key": "j_swashbuckler",
    "name": "Swashbuckler",
    "nameZh": "侠盗",
    "rarity": 1,
    "cost": 4,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "Adds the sell value of all other owned",
    "descriptionZh": "将拥有的所有其他",
    "baseMult": 1
  },
  "j_troubadour": {
    "key": "j_troubadour",
    "name": "Troubadour",
    "nameZh": "游吟诗人",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_certificate": {
    "key": "j_certificate",
    "name": "Certificate",
    "nameZh": "证书",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "When round begins,",
    "descriptionZh": "回合开始时 随机添加一张"
  },
  "j_smeared": {
    "key": "j_smeared",
    "name": "Smeared Joker",
    "nameZh": "模糊小丑",
    "rarity": 2,
    "cost": 7,
    "category": "HAND_MODIFIER",
    "triggerPhase": "hand_modifier",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_throwback": {
    "key": "j_throwback",
    "name": "Throwback",
    "nameZh": "回溯",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "本赛局内每跳过一次",
    "baseXMult": 1.0
  },
  "j_hanging_chad": {
    "key": "j_hanging_chad",
    "name": "Hanging Chad",
    "nameZh": "未断选票",
    "rarity": 1,
    "cost": 4,
    "category": "RETRIGGER",
    "triggerPhase": "retrigger",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "打出的牌中"
  },
  "j_rough_gem": {
    "key": "j_rough_gem",
    "name": "Rough Gem",
    "nameZh": "璞玉",
    "rarity": 2,
    "cost": 7,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的",
    "suit": "Diamonds"
  },
  "j_bloodstone": {
    "key": "j_bloodstone",
    "name": "Bloodstone",
    "nameZh": "血石",
    "rarity": 2,
    "cost": 7,
    "category": "XMULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "打出的",
    "baseXMult": 1.5,
    "suit": "Hearts"
  },
  "j_arrowhead": {
    "key": "j_arrowhead",
    "name": "Arrowhead",
    "nameZh": "箭头",
    "rarity": 2,
    "cost": 7,
    "category": "CHIPS",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的",
    "baseChips": 50,
    "suit": "Spades"
  },
  "j_onyx_agate": {
    "key": "j_onyx_agate",
    "name": "Onyx Agate",
    "nameZh": "缟玛瑙",
    "rarity": 2,
    "cost": 7,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "Played cards with",
    "descriptionZh": "打出的",
    "baseMult": 7,
    "suit": "Clubs"
  },
  "j_glass": {
    "key": "j_glass",
    "name": "Glass Joker",
    "nameZh": "玻璃小丑",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "每摧毁一张",
    "baseXMult": 1.0
  },
  "j_ring_master": {
    "key": "j_ring_master",
    "name": "Showman",
    "nameZh": "马戏团长",
    "rarity": 2,
    "cost": 5,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_flower_pot": {
    "key": "j_flower_pot",
    "name": "Flower Pot",
    "nameZh": "花盆",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌型中，包含",
    "baseXMult": 3.0
  },
  "j_blueprint": {
    "key": "j_blueprint",
    "name": "Blueprint",
    "nameZh": "蓝图",
    "rarity": 3,
    "cost": 10,
    "category": "BLUEPRINT",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "Copies ability of",
    "descriptionZh": "复制"
  },
  "j_wee": {
    "key": "j_wee",
    "name": "Wee Joker",
    "nameZh": "小小丑",
    "rarity": 3,
    "cost": 8,
    "category": "CHIPS",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "This Joker gains",
    "descriptionZh": "",
    "baseChips": 8,
    "ranks": [
      "2"
    ]
  },
  "j_merry_andy": {
    "key": "j_merry_andy",
    "name": "Merry Andy",
    "nameZh": "快乐安迪",
    "rarity": 2,
    "cost": 7,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "每回合"
  },
  "j_oops": {
    "key": "j_oops",
    "name": "Oops! All 6s",
    "nameZh": "Упс! Все шестерки",
    "rarity": 2,
    "cost": 4,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_idol": {
    "key": "j_idol",
    "name": "The Idol",
    "nameZh": "偶像",
    "rarity": 2,
    "cost": 6,
    "category": "FLAT_MULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 2.0
  },
  "j_seeing_double": {
    "key": "j_seeing_double",
    "name": "Seeing Double",
    "nameZh": "重影",
    "rarity": 2,
    "cost": 6,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中，包含",
    "baseXMult": 2.0
  },
  "j_matador": {
    "key": "j_matador",
    "name": "Matador",
    "nameZh": "斗牛士",
    "rarity": 2,
    "cost": 7,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果出牌触发了"
  },
  "j_hit_the_road": {
    "key": "j_hit_the_road",
    "name": "Hit the Road",
    "nameZh": "上路吧杰克",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "本回合中，每弃掉一张",
    "baseXMult": 1.0
  },
  "j_duo": {
    "key": "j_duo",
    "name": "The Duo",
    "nameZh": "二重奏",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseXMult": 2.0,
    "handType": "Pair"
  },
  "j_trio": {
    "key": "j_trio",
    "name": "The Trio",
    "nameZh": "三重奏",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseXMult": 3.0,
    "handType": "Three of a Kind"
  },
  "j_family": {
    "key": "j_family",
    "name": "The Family",
    "nameZh": "一家人",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseXMult": 4.0,
    "handType": "Four of a Kind"
  },
  "j_order": {
    "key": "j_order",
    "name": "The Order",
    "nameZh": "秩序",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseXMult": 3.0,
    "handType": "Straight"
  },
  "j_tribe": {
    "key": "j_tribe",
    "name": "The Tribe",
    "nameZh": "部落",
    "rarity": 3,
    "cost": 8,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果打出的牌中",
    "baseXMult": 2.0,
    "handType": "Flush"
  },
  "j_stuntman": {
    "key": "j_stuntman",
    "name": "Stuntman",
    "nameZh": "特技演员",
    "rarity": 3,
    "cost": 7,
    "category": "CHIPS",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseChips": 250
  },
  "j_invisible": {
    "key": "j_invisible",
    "name": "Invisible Joker",
    "nameZh": "隐形小丑",
    "rarity": 3,
    "cost": 8,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_brainstorm": {
    "key": "j_brainstorm",
    "name": "Brainstorm",
    "nameZh": "头脑风暴",
    "rarity": 3,
    "cost": 10,
    "category": "BRAINSTORM",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "Copies the ability",
    "descriptionZh": "复制最左边的"
  },
  "j_satellite": {
    "key": "j_satellite",
    "name": "Satellite",
    "nameZh": "卫星",
    "rarity": 2,
    "cost": 6,
    "category": "ECONOMY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": "本赛局每使用过一种"
  },
  "j_shoot_the_moon": {
    "key": "j_shoot_the_moon",
    "name": "Shoot the Moon",
    "nameZh": "射月",
    "rarity": 1,
    "cost": 5,
    "category": "FLAT_MULT",
    "triggerPhase": "held_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "留在手牌中的",
    "baseMult": 13,
    "ranks": [
      "Q"
    ]
  },
  "j_drivers_license": {
    "key": "j_drivers_license",
    "name": "Driver",
    "nameZh": "驾驶执照",
    "rarity": 3,
    "cost": 7,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "如果牌组中至少有",
    "baseXMult": 3.0
  },
  "j_cartomancer": {
    "key": "j_cartomancer",
    "name": "Cartomancer",
    "nameZh": "卡牌术士",
    "rarity": 2,
    "cost": 6,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": ""
  },
  "j_astronomer": {
    "key": "j_astronomer",
    "name": "Astronomer",
    "nameZh": "天文学家",
    "rarity": 2,
    "cost": 8,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "",
    "descriptionZh": ""
  },
  "j_burnt": {
    "key": "j_burnt",
    "name": "Burnt Joker",
    "nameZh": "烧焦小丑",
    "rarity": 3,
    "cost": 8,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "Upgrade the level of",
    "descriptionZh": "升级每回合"
  },
  "j_bootstraps": {
    "key": "j_bootstraps",
    "name": "Bootstraps",
    "nameZh": "提靴带",
    "rarity": 2,
    "cost": 7,
    "category": "FLAT_MULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseMult": 2
  },
  "j_caino": {
    "key": "j_caino",
    "name": "Canio",
    "nameZh": "卡尼奥",
    "rarity": 4,
    "cost": 20,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_triboulet": {
    "key": "j_triboulet",
    "name": "Triboulet",
    "nameZh": "特里布莱",
    "rarity": 4,
    "cost": 20,
    "category": "XMULT",
    "triggerPhase": "played_card",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "",
    "baseXMult": 2.0,
    "ranks": [
      "K",
      "Q"
    ]
  },
  "j_yorick": {
    "key": "j_yorick",
    "name": "Yorick",
    "nameZh": "约里克",
    "rarity": 4,
    "cost": 20,
    "category": "XMULT",
    "triggerPhase": "joker_main",
    "blueprintCompat": true,
    "description": "This Joker gains",
    "descriptionZh": "",
    "baseXMult": 1.0
  },
  "j_chicot": {
    "key": "j_chicot",
    "name": "Chicot",
    "nameZh": "希科",
    "rarity": 4,
    "cost": 20,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": false,
    "description": "Disables effect of",
    "descriptionZh": ""
  },
  "j_perkeo": {
    "key": "j_perkeo",
    "name": "Perkeo",
    "nameZh": "帕奇欧",
    "rarity": 4,
    "cost": 20,
    "category": "UTILITY",
    "triggerPhase": "passive",
    "blueprintCompat": true,
    "description": "",
    "descriptionZh": "在离开商店时",
    "handType": "Pair",
    "suit": "Spades"
  }
};

/**
 * Normalized lookup by key or English/Chinese label
 */
const JOKER_LOOKUP_MAP = new Map<string, JokerDefinition>();

for (const def of Object.values(BALATRO_JOKERS)) {
  JOKER_LOOKUP_MAP.set(def.key.toLowerCase(), def);
  JOKER_LOOKUP_MAP.set(def.name.toLowerCase(), def);
  JOKER_LOOKUP_MAP.set(def.nameZh.toLowerCase(), def);
  // Also stripped versions
  const strippedKey = def.key.replace(/^j_/, '').replace(/_/g, ' ').toLowerCase();
  JOKER_LOOKUP_MAP.set(strippedKey, def);
  const cleanKey = def.key.replace(/^j_/, '').replace(/_/g, '').toLowerCase();
  JOKER_LOOKUP_MAP.set(cleanKey, def);
}

export function getJokerDefinition(query?: string | null): JokerDefinition | undefined {
  if (!query) return undefined;
  const q = query.trim().toLowerCase();
  const direct = JOKER_LOOKUP_MAP.get(q);
  if (direct) return direct;

  // Partial search if not found
  for (const [k, def] of JOKER_LOOKUP_MAP.entries()) {
    if (k.length > 3 && (q.includes(k) || k.includes(q))) {
      return def;
    }
  }
  return undefined;
}
